# Item: Getting Started With PyTorch

#### References

1. **What is PyTorch:** https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

## Getting Started With PyTorch

PyTorch is a popular framework for deep learning. In this item, we will describe some of its core features.

In [14]:
# as usual we need to import the module
import torch

### Tensors

Tensors are similar to NumPy arrays. However,we can also  use them on GPUs to accelerate computing. Let's see some examples of using Tensors in PyTorch

In [15]:
# construct empty matrix
matrix = torch.empty(5,5)
matrix

tensor([[1.0720e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [16]:
# construct randmly initialized matrix
matrix = torch.rand(5,5)
matrix

tensor([[0.9661, 0.8207, 0.6129, 0.7986, 0.5214],
        [0.6392, 0.9071, 0.7086, 0.9658, 0.3886],
        [0.2303, 0.2528, 0.3829, 0.2578, 0.6786],
        [0.6627, 0.6228, 0.3234, 0.9426, 0.0506],
        [0.0110, 0.6622, 0.0574, 0.5028, 0.5594]])

In [17]:
# we can also specify the type of the element the tensor holds
matrix = torch.zeros(5, 3, dtype=torch.long)
matrix

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
# we can also initialize a sensor by setting directly its data
matrix = torch.tensor([5.5, 3])

In [12]:
# similar to numpy shape property, we have the size function that informs us about the size of the matrix
matrix = torch.zeros(2,2)
matrix.size()

torch.Size([2, 2])

---

**Remark**


```torch.Size``` is in fact a tuple, so it supports all tuple operations.

---

### Operations

Let's now see how we can apply various operations on tensors. In fact, there are multiple syntaxes for operations.

In [19]:
# Synatx 1
y = torch.rand(5, 3)
x = torch.rand(5,3)
y+x

tensor([[1.6044, 0.0662, 1.4340],
        [0.9219, 0.5674, 0.6272],
        [0.5570, 0.4579, 1.0145],
        [1.0862, 0.9393, 1.4166],
        [0.9808, 0.3560, 1.0491]])

In [21]:
# Syntax 2 
z = torch.add(y, x)
z

tensor([[1.6044, 0.0662, 1.4340],
        [0.9219, 0.5674, 0.6272],
        [0.5570, 0.4579, 1.0145],
        [1.0862, 0.9393, 1.4166],
        [0.9808, 0.3560, 1.0491]])

In [22]:
# Synatx 3
out = torch.empty(y.size())
torch.add(x, y, out=out)
out

tensor([[1.6044, 0.0662, 1.4340],
        [0.9219, 0.5674, 0.6272],
        [0.5570, 0.4579, 1.0145],
        [1.0862, 0.9393, 1.4166],
        [0.9808, 0.3560, 1.0491]])